## 사이킷런으로 시작하는 머신러닝
### 붓꽃 품종 예측하기
##### -먼저 붓꽃 데이터를 사용할수 있게 해주고, 분류에 쓸 함수들을 가져오기

In [6]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split
import pandas as pd
iris = load_iris()
iris_data= iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [9]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names) 
iris_df
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [10]:
# -iris_df['label'] = iris.target   
# (iris_df) <-이 데이터 프레임에 iris.target인 0~2를 함께 볼수 있도록 'label'이라는 이름의 열을 추가해 줍니다. 
iris_df['label'] = iris.target 
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

##### -학습된 모델의 성능을 알아보기 위해 학습용 데이터와 테스트용 데이터를 분리시켜 주기

In [11]:
# iris 데이터중 80프로는 학습용, 나머지 20프로는 테스트용으로 분할한다
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2,random_state=11)

##### -의사결정 트리로 학습 후 예측하고, 성능(정확도)평가하기

In [12]:
#학습 시킬때 의사결정 트리씀
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [13]:
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 2])

In [14]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test,pred)))
# 테스트용 레이블 데이터(y_test)와 예측된 레이블 데이터(pred)의 정확성이 약 0.98입니다.

예측 정확도: 0.866667


### 사이킷런의 기반 프레임워크 익히기

In [15]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))
# 결과가 Bunch로 나오는 데 번치 클래스는 파이썬 딕셔너리 자료형과 유사함.

<class 'sklearn.utils.Bunch'>


In [16]:
#데이터 세트에 내장돼 있는 대부분의 데이터 세트는 아래와 같이 딕셔너리 형태의 값을 반환함.
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)
#data가 피처 값, target이 레이블 값

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [55]:
#딕셔너리 형태에서 피처 데이터 값을 추출하려면 데이터 세트.data or 데이터 세트['data']헤주면 됨
#나는 데이터 세트 설명과 각 피처의 설명을 나타내는 DESCR을 쳐봄. DESCR는 표에는 안나오니까..?
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [17]:
print(' feature_names 의 type:', type(iris_data.feature_names))
print(' feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data['feature_names'])

print('\n target의 type:', type(iris_data.target))
print(' target의 shape:', iris_data.target.shape)
print(iris_data.target)

 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target의 type: <class 'numpy.ndarray'>
 target의 shape: (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### k폴드 교차검증 
* 데이터 편중을 막고자, 여러번 다양하게 데이터 구성시켜 학습 및 평가
* 데이터를 k덩이로 나눠서 k개 중 1개는 검증, 나머지 k-1 개는 학습으로 분할하는 걸 각각 다르게! k번한다.
* (1) 폴드 세트 설정 
* (2) for 루프 반복으로 학습 및 테스트 데이터의 인덱스를 추출 
* (3) 반복적으로 학습과 예측을 수행하고 예측수행을 반환

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

iris.data.shape[0]
# +) shape[0] 은 행의 개수, shape[1] 은 열의 개수 인가봄
# 근데 여기서 붓꽃 데이터가 150개라고 하는데 shape로 보면 행이 150, 열이 4개
# 그래서 데이터는 600개 라고 생각할수 있지만, 4개의 열을 큰 하나로 보나봄. 큰 틀에서 그 피처를 가지는 꽃 종류는 같은거니까

150

In [103]:
#(1)
kfold=KFold(n_splits=5)
cv_accuracy=[]

# 교차검증의 횟수를 세기 위한 변수로 n_iter를 지정해 줍니다.
n_iter=0

#(2)
for train_index, test_index in kfold.split(features):
    # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test=features[train_index], features[test_index]
    y_train, y_test=label[train_index], label[test_index]
#(3)    
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    n_iter +=1
    # 반복 시마다 정확도 측정
    accuracy=np.round(accuracy_score(y_test, pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n#{0} 교차 검증 정확도:{1}, 학습 데이터 크기: {2}, 검증 데이터 크기:{3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    print('#{0} 학습 용:{1}'.format(n_iter, train_index))
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))

#iteration이란..음..


#1 교차 검증 정확도:1.0, 학습 데이터 크기: 120, 검증 데이터 크기:30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
#1 학습 용:[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

#2 교차 검증 정확도:0.9667, 학습 데이터 크기: 120, 검증 데이터 크기:30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
#2 학습 용:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  7

In [100]:
# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환해줌.
# 문자열.split() 함수는 문자열을 일정한 규칙으로 잘라서 리스트로 만들어 주는 함수.
# n_splits 는 데이터 분할 수 입니다. 그러면 이 숫자만큼 인덱스로 분할함. 전체 데이터 수를 넘을 수 없습니다. (=분할 파라미터를 설정)
# +) shuffle은  매번 데이터를 분할하기전 섞을지 말지 여부를 선택합니다. 기본값이 트루인가?

# KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환해줌.
# StratifiedKFold 사용을 위해서는 레이블 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에 
# split( ) 메서드에 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트도 반드시 넣어줘야한다.
# 문자열.split() 함수는 문자열을 일정한 규칙으로 잘라서 리스트로 만들어 주는 함수.
# 그리고 split() 함수 써주면 값이 인덱스로 반환됨
# 위에서 검증(=테스트용) 세트 인덱스만 출력한 이유가 학습용까지 출력하면 #1에서는 30~149 #2에서는 0~29, 60~149..너무 많아서 그럼

In [9]:
test_index

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149])

In [10]:
train_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [76]:
import pandas as pd

iris=load_iris()
iris_df=pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()
# 시리즈의 값이 정수, 문자열, 카테고리 값인 경우에는 value_counts() 메서드로 각각의 값이 나온 횟수를 셀 수 있음.

0    50
1    50
2    50
Name: label, dtype: int64

In [77]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
    n_iter +=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차검증:{0}\n'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    
# iloc[0]은 전체 데이터 프레임에서 0번째 행의 값들만 추출해라
# print형식 써줄때 값 입력 부분에서 언제 format쓰고 언제는 걍 값 그자체를 써주는가..질문

## 교차검증:1

학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차검증:2

학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차검증:3

학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [34]:
kfold.split(iris_df)

<generator object _BaseKFold.split at 0x000001F557762890>

In [35]:
train_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [14]:
test_index

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [16]:
label_train

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: label, Length: 100, dtype: int32

In [2]:
# 계속 헷갈리는 것-(값 추출과 열 추가)
# '딕셔너리 형태'에서 피처 데이터 값을 추출하려면 데이터 세트.data or 데이터 세트['data']헤주면 됨
# iris_df['label'] = iris.target: '데이터 프레임'에 iris.target인 0~2를 함께 볼수 있도록 'label'이라는 이름의 열을 추가
# 그러면 데이터 프레임에 딕셔너리는 포함 안되고 완전히 다른건가 봄..? 질문각

#### +) k폴드 추후 학습

In [30]:
# 이 데이터를 2덩이로 나눠서 한덩이는 검증. 나머지 한덩이는 학습으로 분할하는걸 각각 다르게! 2번 해줌.
X=[1,2,3]
kfold=KFold(n_splits=2)
for train_index, test_index in kfold.split(X): 
    print(train_index)
    print(test_index)
print(kfold.split(X))

[2]
[0 1]
[0 1]
[2]
<generator object _BaseKFold.split at 0x000002B7B6A4F200>


In [39]:
# 이 데이터를 3덩이로 나눠서 1/3은 검증,2/3은 학습으로 분할하는 걸 3번한다.
# 그리고 split의 값은 인덱스로 나온다.
X=[1,2,3]
kfold=KFold(n_splits=3)
for train_index, test_index in kfold.split(X): 
    print(train_index)
    print(test_index)
print(kfold.split(X))

[1 2]
[0]
[0 2]
[1]
[0 1]
[2]
<generator object _BaseKFold.split at 0x000002B7B6A74190>


In [78]:
from sklearn.model_selection import KFold
# train_test_Split 메서드도 이 모듈에 있었음

kfold = KFold(n_splits = 5)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('##교차 검증:{0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

##교차 검증:1
학습 레이블 데이터 분포:
 1    50
2    50
0    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    30
Name: label, dtype: int64
##교차 검증:2
학습 레이블 데이터 분포:
 2    50
1    40
0    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    20
1    10
Name: label, dtype: int64
##교차 검증:3
학습 레이블 데이터 분포:
 0    50
2    50
1    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    30
Name: label, dtype: int64
##교차 검증:4
학습 레이블 데이터 분포:
 0    50
1    40
2    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    20
1    10
Name: label, dtype: int64
##교차 검증:5
학습 레이블 데이터 분포:
 0    50
1    50
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    30
Name: label, dtype: int64


In [4]:
#이게 내가 헷갈렸던게 3가지의 다른 레이블을 가진 150개의 데이터를 50개씩 3개의 덩어리로 나눠 예측하니까 
#학습데이터와 검증 데이터의 레이블이 겹칠수가 없음. 따라서 정확도가 0이 나올수 밖에 없는 구조임
#(그래서 이거 대안책이 StratifiedKFold임 <-전체 레이블 값의 분포도를 반영하게 해줌)

#반면 3가지의 다른 레이블을 가진 150개의 데이터를 30개씩 5개의 덩어리로 나눠 예측하면 학습데이터와 검증 데이터의
#레이블이 겹침. 그래서 정확도가 꽤 괜찮게 나옴. 이건 위의 식의 학습 및 검증 레이블 데이터 분포 참고하면 알수 있음

# +)참고로, 같은 데이터라고 조합이 다르면 다른 정확도가 나올수 있음. 위의 ##교차검증:1과 ##교차검증:5에서 처럼

### StratifiedKFold
* KFold로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결해줌
* 레이블 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에, split() 메서드에 인자로 피처뿐만 아니라 레이블 데이터 세트도 반드시 필요함

In [20]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter +=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
    
# 아래 출력 결과를 보면 학습 레이블과 검증 레이블 데이터 값의 분포도가 동일하게 할당됐음을 알 수 있다.

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


##### -StratifiedKFoldfmf 이용해 데이터 분리하기

In [21]:
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
    #split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test=features[train_index],features[test_index]
    y_train, y_test=label[train_index], label[test_index]
    #학습 및 에측
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    
    #반복 시마다 정확도 측정
    n_iter +=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy,4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


In [2]:
#여기서 질문이 features의 값을 인덱스로 바꾸고 다시 값으로 반환해 주는 건가?
#print('~~')쓸때 {0}, {1}이 있으면 그 순서에 맞게 format( , )있어야 함, {0}이런거 없으면 그냥 뒤에 오는 값 넣주기
# +)사실 k폴드가 아니라 StratifiedKFold를 쓰는게 맞음
# 근데 회귀에서는 StratifiedKFold를 지원하지 않음. 
# 회귀의 결정값은 이산값 형태의 레이블이 아니라 연속된 숫자값이기 때문에 결정값별로 분초를 정하는 의미가 없다.
# 그래서 다음으로 이런 교차 겁증을 보다 간편하게 제공해주는 사이킷런의 API를 살펴볼거당

### cross_val_score() : 교차 검증을 보다 간편하게 제공해주는 사이킷런의 API 
* KFold의 과정을 한꺼번에 수행하는 API임
* (1) 폴드 세트 설정, (2) for 루프 반복으로 학습 및 테스트 데이터의 인덱스를 추출,(3) 반복적으로 학습과 예측을 수행하고 예측수행을 반환 -->이 과정을 한꺼번에
* cross_val_score( estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs' ) 형태로 이뤄짐
* cross_val_score( 사이킷런의 분류 또는 회귀 알고리즘, 피처 데이터 세트, 레이블 데이터 세트, 예측 성능 평가, 교차 검증 폴드 수, n_jobs=1, verbose=0, fit_params=None, pre_dispatch='2*n_jobs' )

In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores=cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:' ,np.round(np.mean(scores),4))

#cross_val_score()에 classifier가 입력되면 기본적으로 Stratified K폴드 방식으로 레이블값의 분포에 따라 
# 학습 및 테스트 세트로 분할 하는데, 회귀인 경우 Stratified K폴드 방실으로 분할 못해서 K폴드 방식으로 분할함
#질문인데 cross_val_score에서 '사이킷런의 분류 또는 회귀 알고리즘' 자리에 의사결정 트리가 왜 나와?

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


##### +) cross_validate: cross_val_score()와는 달리 여러개의 평가 지표를 반환할수 있음. 일단 건너뛰겠음

### GridSearchCV: 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에 할수 있음
* 하이퍼 파라미터는 머신러닝 알고리즘을 구성하는 주요 구성 요소이며, 이 값을 조정해 알고리즘의 예측성능을 개선할 수 있다.
* GridSearchCV API를 이용해 분류나 회귀 알고리즘에 이용되는 하이퍼 파라미터를 순차적으로 이력하며 최적의 파라미터 도출할 수 있는 방안을 제공(촘촘하게 파라미터 입력하며 테스트 하는 방식)

-하이퍼 파라미터를 순차적으로 변경하며 최적의 파라미터 도출하고자 한다면 다음과 같이 파라미터 집합을 만들고 이를 순차적으로 적용하면 됨

In [110]:
#얘는 왜쓴건지 모르겠네..
grid_parameters={'max_depth':[1,2,3],
                 'min_samples_split':[2,3]
                }
grid_parameters

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [3]:
#cv가 3회라면 개별 파라미터 조합마다 3개의 폴딩 세트를 3회에 걸쳐 학습 및 평가에 쳥균값으로 성능을 측정함
#6개의 파라미터 조합이라면 총 cv 3회* 6개의 파라미터 조합=18회의 학습 및 평가가 이뤄짐

In [23]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data=load_iris()
X_train, X_test, y_train, y_test=train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree=DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [25]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나ㄴ우어 테스트 수행 설정.
### refit=True가 기본값임. True이면 가장 좋은 마파미터 설정으로 재학습시킴.
grid_dtree=GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95